# Generated by Django 3.2 on 2022-10-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lat_deliver',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lat_pickup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lng_deliver',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lng_pickup',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
